import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResumeStepper from "./ui/resume-stepper";
import ResumeContextProvider from "./ui/resume-context-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         {/* <div className="container mx-auto bg-green-500 overflow-hidden"> */}
          <ResumeContextProvider>
            <ResumeStepper />
            <div className="w-full bg-amber-500">
              {children}
            </div>
          </ResumeContextProvider>
           
          
        {/* </div> */}
        
      </body>
    </html>
  );
}
